# Increased heap size for Gradle daemon to avoid OutOfMemoryError
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Android standard properties
android.useAndroidX=true
android.enableJetifier=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
